#   Entity Supports (Exact):
#     Bat, Bee, Blaze, Cat, Cave Spider, Chicken, Cod, Cow, Creeper, Donkey, Dolphin
#     Drowned, Elder Guardian, Enderman, Ender Dragon, Endermite, Evoker, Fox, Giant
#     Ghast, Guardian, Hoglin, Horse, Husk, Illusioner, Iron Golem, Llama, Magma Cube
#     Mule, Mooshroom, Ocelot, Panda, Parrot, Phantom, Pig, Piglin, Piglin Brute
#     Pillager, Polar Bear, Pufferfish, Rabbit, Ravager, Salmon, Sheep, Shulker, Silverfish
#     Skeleton, Skeleton Horse, Slime, Snowman, Spider, Squid, Stray, Strider, Trader Llama
#     Tropical Fish, Turtle, Vex, Villager, Vindicator, Wandering Trader, Witch, Wither
#     Wither Skeleton, Zoglin, Zombie, Zombie Horse, Zombie Villager, Zombified Piglin
#   Enchantment Supports (Exact):
#     Power, Punch, Sharpness, Bane of Arthropods, Smite, Efficiency, Unbreaking
#     Fire Aspect, Frost Walker, Impaling, Knockback, Fortune, Looting, Loyalty
#     Luck of the Sea, Lure, Respiration, Piercing, Protection, Blast Protection
#     Feather Falling, Fire Proection, Projectile Protection, Quick Charge, Riptide
#     Soul Speed, Sweeping Edge, Thorns
#
#   Usage:
#
#   Standard Mob
#   Entity Name (exact):
#     Enchantment Name (exact): % Drop Chance
#     Enchantment Name (exact): % Drop Chance
#     ...
#
#   Book Dropping Mob
#   Entity Name (exact):
#     Book: true
#     Enchantment Name (exact): % Drop Chance
#     ...
#
#   Default Values:
#
Blaze:
  Sharpness: 0.059
  Fire Protection: 0.17
  Fire Aspect: 0.5
  Projectile Protection: 0.13
Cave Spider:
  Bane of Arthropods: 0.33
  Feather Falling: 0.13
  Efficiency: 0.2
Creeper:
  Sharpness: 0.059
  Blast Protection: 0.5
  Knockback: 0.17
Drowned:
  Smite: 0.1
  Respiration: 0.33
  Riptide: 0.1
  Loyalty: 0.1
  Projectile Protection: 0.13
Elder Guardian:
  Imapling: 50
  Respiration: 33
  Thorns: 50
  Luck of the Sea: 50
  Lure: 50
  Depth Strider: 50
Enderman:
  Sharpness: 0.059
  Feather Falling: 0.13
  Looting: 0.13
  Efficiency: 0.2
  Protection: 0.11
Ender Dragon:
  Book: true
  Power: 4
  Punch: 4
  Sharpness: 4
  Bane of Arthropods: 4
  Smite: 4
  Depth Strider: 4
  Efficiency: 4
  Unbreaking: 4
  Fire Aspect: 4
  Frost Walker: 4
  Impaling: 4
  Knockback: 4
  Fortune: 4
  Looting: 4
  Loyalty: 4
  Luck of the Sea: 4
  Lure: 4
  Respiration: 4
  Piercing: 4
  Protection: 4
  Blast Protection: 4
  Feather Falling: 4
  Fire Protection: 4
  Projectile Protection: 4
  Quick Charge: 4
  Riptide: 4
  Soul Speed: 4
  Sweeping Edge: 4
  Thorns: 4
Endermite:
  Bane of Arthropods: 0.33
Evoker:
  Sharpness: 5.9
  Looting: 13
  Protection: 11
Ghast:
  Sharpness: 0.059
  Knockback: 0.17
  Blast Protection: 0.5
  Fire Protection: 0.17
  Projectile Protection: 0.13
  Fire Aspect: 0.5
Guardian:
  Imapling: 0.5
  Respiration: 0.33
  Thorns: 0.5
  Luck of the Sea: 0.5
  Lure: 0.5
  Depth Strider: 0.5
Hoglin:
  Sharpness: 0.059
  Knockback: 0.17
  Protection: 0.11
  Unbreaking: 0.2
Iron Golem:
  Sharpness: 0.059
  Knockback: 0.17
  Protection: 0.11
  Unbreaking: 0.2
Husk:
  Smite: 0.1
Magma Cube:
  Sharpness: 0.059
  Frost Walker: 0.5
  Knockback: 0.17
  Fire Protection: 0.17
  Sweeping Edge: 0.33
  Feather Falling: 0.13
Phantom:
  Smite: 0.1
  Feather Falling: 0.13
  Looting: 0.13
  Efficiency: 0.2
Piglin:
  Sharpness: 0.059
  Quick Charge: 0.5
  Piercing: 0.5
  Fortune: 0.25
  Projectile Protection: 0.13
Piglin Brute:
  Sharpness: 5.9
  Protection: 1.1
  Fortune: 5
  Efficiency: 2
Pillager:
  Sharpness: 0.059
  Quick Charge: 0.5
  Piercing: 0.5
  Projectile Protection: 0.13
Ravager:
  Sharpness: 0.59
  Knockback: 1.7
  Protection: 1.1
  Unbreaking: 2
Shulker:
  Sharpness: 0.059
  Feather Falling: 0.13
  Looting: 0.13
  Projectile Protection: 0.13
Skeleton:
  Smite: 0.1
  Power: 0.5
  Punch: 0.5
  Projectile Protection: 0.13
Stray:
  Smite: 0.1
  Power: 0.5
  Punch: 0.5
  Projectile Protection: 0.13
Slime:
  Sharpness: 0.059
  Frost Walker: 0.5
  Knockback: 0.17
  Sweeping Edge: 0.33
  Feather Falling: 0.13
Silverfish:
  Bane of Arthropods: 0.33
  Efficiency: 0.2
Spider:
  Bane of Arthropods: 0.33
  Feather Falling: 0.13
  Efficiency: 0.2
Vex:
  Sharpness: 0.59
  Protection: 1.1
  Feather Falling: 1.3
Vindicator:
  Sharpness: 0.059
  Looting: 0.13
  Protection: 0.11
Witch:
  Sharpness: 0.59
  Looting: 1.3
  Unbreaking: 2
Wither:
  Book: true
  Power: 2
  Punch: 2
  Sharpness: 2
  Bane of Arthropods: 2
  Smite: 2
  Depth Strider: 2
  Efficiency: 2
  Unbreaking: 2
  Fire Aspect: 2
  Frost Walker: 2
  Impaling: 2
  Knockback: 2
  Fortune: 2
  Looting: 2
  Loyalty: 2
  Luck of the Sea: 2
  Lure: 2
  Respiration: 2
  Piercing: 2
  Protection: 2
  Blast Protection: 2
  Feather Falling: 2
  Fire Protection: 2
  Projectile Protection: 2
  Quick Charge: 2
  Riptide: 2
  Soul Speed: 2
  Sweeping Edge: 2
  Thorns: 2
Wither Skeleton:
  Smite: 0.1
  Looting: 0.13
  Soul Speed: 0.1
  Fire Protection: 0.17
Zombie:
  Smite: 0.1
Zombie Villager:
  Smite: 0.1
  Fortune: 0.25
  Looting: 0.13
Zombified Piglin:
  Smite: 0.1
  Looting: 0.2
  Fire Protection: 0.17
  Sweeping Edge: 0.33



